
package com.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T19:54:59.095+08:00
 * Generated source version: 3.3.4
 *
 */
public final class DemoService_DemoServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.demo.webservice.com", "DemoService");

    private DemoService_DemoServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        DemoService_Service ss = new DemoService_Service(new URL("http://localhost:9999/demo/demo/api?wsdl"), SERVICE_NAME);
        DemoService port = ss.getDemoServiceImplPort();

        {
        System.out.println("Invoking sayHello...");
        String _sayHello_arg0 = "12332\n\r";
        String _sayHello__return = port.sayHello(_sayHello_arg0);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
