package com.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T19:54:59.161+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://service.demo.webservice.com", name = "DemoService")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.demo.webservice.com", className = "com.webservice.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.demo.webservice.com", className = "com.webservice.client.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(

			@WebParam(name = "arg0", targetNamespace = "")
					String arg0
	);
}
